name: Test Windows - build of Rust examples

on:
  workflow_dispatch:
    inputs:
      rust_build_branch:
        description: 'Branch with test scripts'
        required: true
        default: 'main'
      toolchain_version:
        description: 'Version of Rust IDF toolchain'
        required: true
        default: '1.61.0.0'

jobs:
  build-idf-rust-examples:
    name: Build IDF Rust Examples for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.rust_build_branch }}
      - uses: ./.github/actions/tools/setup-python
      - uses: ./.github/actions/tools/setup-ninja

      # Work around the windows path issue
      - name: Symlink the working dir
        shell: pwsh
        run: New-Item -Path D:/build -ItemType SymbolicLink -Value ${{ github.workspace }}

      - name: Test Rust toolchain by compiling STD demo
        working-directory: D:/build
        shell: pwsh
        run: .\Test-RustToolchain.ps1 -ToolchainVersion ${{ github.event.inputs.toolchain_version }}
